### ISSUE TITLE
How to draw curves and custom shapes

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#251]
Hey there,

I just discovered this framework, and it feels very easy and straightforward to create apps with it. Really nice work here 👌🏾

I started an app with it and as a requirement I need to create a kind of curve editor, where the user can create a custom curve using beizer control points. Also I will need to draw custom shapes like circles and ellipsises.

Currently it seems that the renderer API can only draw lines and rectangles... Is there a way or a workaround to achieve my goal with the current state of the project?

**Comment by Alex2772** [comment]
Hello,

Thank you for your interest to the project!

You may want to use [ARender::lines](https://aui-framework.github.io/develop/classARender.html#a70088c033cf80d08c85e84ea8959ce04) like [in example](https://github.com/aui-framework/aui/blob/master/examples/AUI.Example.Views/src/DemoGraphView.cpp). It draws straight lines though, but you can precalculate bezier curve points and draw the curve using straight lines.

When it's not enough, we use SVG by directly accessing SVG classes from `aui.image`:

```cpp
void DemoGraphView::render(ClipOptimizationContext context) {
    AView::render(context);

    auto d = std::make_shared<AVectorDrawable>(std::make_shared<SvgImageFactory>(AByteBufferView(std::string_view(R"s(
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="256px" height="256px" viewBox="0 0 256 256" enable-background="new 0 0 256 256" xml:space="preserve">
<polyline points="14.001,61.469 14.001,198.082 125.667,141.363 125.667,4.75 "/>
<polyline fill="none" stroke="#000000" stroke-miterlimit="10" points="14.001,62.264 125.667,5.598 237.334,62.264 "/>
<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="147.332" y1="13.8965" x2="103.1122" y2="104.5606" gradientTransform="matrix(1 0 0 -1 0 256.9238)">
	<stop  offset="0" style="stop-color:#305491"/>
	<stop  offset="1" style="stop-color:#0071AF"/>
</linearGradient>
<polyline fill="url(#SVGID_3_)" points="14.001,123.75 125.667,70.5 125.667,141.363 14.001,198.082 "/>
</svg>
    )s"))));

    d->draw({
        .size = {16, 16}
    });
}
```

**Comment by Alex2772** [comment]
Waiting for feedback!

Currently we targeted at supporting multiple graphics APIs to render (e.g. Vulkan, DirectX, Metal) and performance, so the rendering pipelines are unstable and they are being revised time to time.

If you looking for Canvas API in terms of rendering to texture, we don't have plans for that, as SVG is enough for such use case. It might be planned in future after introducing support of Vulkan.

In terms of performance, we currently have plans of automatically render some parts of UI to texture.

In terms of clipping, we have `AOverflow::HIDDEN` which acts like CSS3 `overflow: hidden`.

Hope this helps.

**Comment by na2axl** [comment]
Hey @Alex2772 

Finally went through my curve editor view, and the usage of SVG worked very well for me, here is a video of the result:

https://github.com/aui-framework/aui/assets/14062034/6220a8f0-dc0e-4420-a537-33e1b60a7043

One of the issues I had was with the framework itself which was giving me linking errors when trying to use `AVectorDrawable`. I fixed the issue in my fork and also added small non-breaking changes. I will propose a pull request in some time.

**Comment by Alex2772** [comment]
Hi @na2axl ,

Looks so smooth! Yeah you may encounter some linking issues, as AVectorDrawable was not intended as a public API; we use static linking so linking errors are rare for us.

Thank you for your feedback.

**Comment by Alex2772** [comment]
Closing as the issue seems resolved.
