### ISSUE TITLE
`sqlite` component not available?

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#256]
Hey there,

I got an issue when I want to use the `sqlite` component. I'm using AUI.Boot to pull components as explained in the documentation. It works well for other components but only the `sqlite` one is not found.

There is how I'm using AUI.Boot:
```cmake
auib_import(
    AUI https://github.com/aui-framework/aui
    COMPONENTS core views json image sqlite
)
```

And how I'm linking:
```cmake
aui_link(
    studio
    PUBLIC
        mimalloc SparkyStudios::Audio::Amplitude::SDK::Shared
    PRIVATE
        aui::core aui::views aui::json aui::image aui::sqlite
)
```

The CMake output have too much info but in some place it says:
```text
Component sqlite is not found
```

Is there a reason it is not available?

**Comment by Alex2772** [comment]
Hi there,

This module is outdated and it's not currently maintained. We should have removed the reference from `README.md`. We have a plans to revisit `aui.data`, `aui.mysql`, `aui.sqlite` modules though.

**Comment by na2axl** [comment]
Oh I see, I will need to directly use the sqlite C++ sdk I feel.

By the way, what are the changes you planed for these packages? I may be able to contribute.

**Comment by Alex2772** [comment]
Outdated code and singletones should be removed, tests are needed, documentation should be written.

**Comment by Alex2772** [comment]
You can propose an API that you would expect from `aui.sqlite` so it satisfies both ours and yours usecase.

**Comment by na2axl** [comment]
Ok got it. I will see what has been done and think about something. I will open a discussion instead for further guidance.

**Comment by Alex2772** [comment]
> Ok got it. I will see what has been done and think about something. I will open a discussion instead for further guidance.

Hi there! How is it going? If you need assistance, I'm happy to help.

**Comment by na2axl** [comment]
Hey @Alex2772, sorry I didn't yet investigated in this. I have a deadline to release a first version of the app I'm building with AUI for the end of this month so for now I just used `aui.json` for a simple JSON database...

For now I will just open a PR with my not-too-noisy updates I did during the development of my app.
