### ISSUE TITLE
Rethink AJson object container approach

### ISSUE THREAD

**Issue by Alex2772** [aui-framework/aui#265]
This discussion is started in #261.

Summary: we need a way to keep order of fields in `AJson` (`Json::Object`).

I generally agree that order should be kept in json objects, but `unordered_map` does not guarantee the persistence of order. Another container should be used. Even `std::vector<std::pair<AString, AJson>>` seems acceptable. Furthermore, you may take a look at `ASmallVector`.

[nlohmann json](https://github.com/nlohmann/json/) uses `std::map` as the default container for object. It also offers alternative object type which is implemented as vector of string-json pair. https://json.nlohmann.me/features/object_order/

_Originally posted by @Alex2772 in https://github.com/aui-framework/aui/issues/261#issuecomment-2016961465_

@na2axl

**Comment by Alex2772** [comment]
I've added Google Benchmark initial support (#262). I'll check for performance of `vector` variant in my spare time.

**Comment by na2axl** [comment]
For this maybe a `AJsonObject` class which extends `AVector<std::pair<AString, AJson>>` and adds index operators for `AString` ?

**Comment by Alex2772** [comment]
> For this maybe a `AJsonObject` class which extends `AVector<std::pair<AString, AJson>>` and adds index operators for `AString` ?

I think I will come up with something like this.

**Comment by na2axl** [comment]
Hey @Alex2772, I don't know if you still have plans for this but I can confirm the new `AJsonObject` implementation works fine for my use case 🎉

**Comment by Alex2772** [comment]
Hi @na2axl, great news! There are no extra work planned on this, so we can close this as resolved.
