### ISSUE TITLE
Switch to Mozilla Public License

### ISSUE THREAD

**Issue by Alex2772** [aui-framework/aui#294]
As AUI is currently licensed under LGPL, it allows to make and sell proprietary software built with AUI. However, it requires LGPL code to be replaceable. So the project that uses AUI should provide a way to replace their compiled AUI binaries by any other version of AUI. This renders static linking to be almost unusable (at least businesses would not want to deal with it). Rebuilding Android's APKs and iOS's app bundle would require to provide the signing key original app was built with. Needless to say that no one would want to deal with it.

I personally don't care about the possibility to replace binaries inside someone's software. I don't care someone makes money with my code. I just want AUI to be useful and potentially improved by other projects with minimal limitations to them.

I suggest to switch to MPL. It's more permissive to user. It requires to publish changes of covered code (like LGPL) and preserves our trademarks. But in comparison to LGPL, other projects can use the covered code (AUI under MPL) in combination with any other terms (including selling) without requiring to provide an ability to replace licensed code (AUI's). So, it's essentially the same, but finally allows to use AUI in proprietary projects that use static linking, signed APK's and signed app bundles without providing the source of their projects or object files. If they distribute their application they need to provide a link to this repository or a repository with their changes to AUI (if any). They even may want to commit their changes to this repository (upstream) as they've already opensourced their changes to AUI (due to MPL obligation). If a company uses changed version of AUI internally only, they are not obligated to opensource though (private usage).

**Comment by Alex2772** [comment]
@na2axl we need your agreement to license switch.

**Comment by na2axl** [comment]
Thanks for notifying me, I was not aware of this switch. I think on my side I'm OK with the MPL, as you said it will allow me to use AUI with static linking, something I have avoided so far due to LGPL.

Once you will do the switch I will update the licenses section of app to reflect the changes 👍🏾

**Comment by Alex2772** [comment]
One interesting detail about LGPL I've discovered recently: modification of a library covered by LGPL applies stronger restrictions to proprietary software, making it risky to use. To hedge the risks, committing changes to the LGPL library to its upstream is considered as the best option (surprisingly). So, instead of making fast ass dirty patch that works literally for your project only, you have to invest time and money to develop your changes so they are good enough to pass the review of the upstream. This is better for libraries, not for businesses that will use the library.

MPL, on the other hand, does not require upstreaming. it does not even require making the changes to be publically available for everyone, just for those who received an "Executable Form" (in terms of MPL). So, in comparison to LGPL, upstreaming is an option. This is better for businesses, not for a library.

The only reason I see why a business may want to upstream changes to the MPL library is to avoid merge conflicts burden.

I'll not change the license of AUI, just wanted to share this detail.
