### ISSUE TITLE
3D View

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#299]
Hey @Alex2772,

I was wondering if and how is it possible to have a 3D View in an app using AUI. Is there a way to achieve this?

**Comment by Alex2772** [comment]
Hi @na2axl,

AUI uses OpenGL for hardware accelerated drawing. You can override `render` method and use OpenGL directly to draw anything you want (including games).

AUI does not provide 3D engine (like Qt 3D, JavaFX) at the moment.

**Comment by na2axl** [comment]
Your hint makes me remember that I saw something like that in the examples in the past haha. Thanks for the answer.
