### ISSUE TITLE
wav playback is broken

### ISSUE THREAD

**Issue by Alex2772** [aui-framework/aui#309]

**Comment by Arcnor** [comment]
At least one problem seems to be that the WAV parser expects wav files without any chunks other than `fmt` and `data` (and I'm not even sure it correctly skips the `data` tag?). In any case, using a proper library for parsing WAV might make sense instead of reinventing the wheel here :).

**Comment by Alex2772** [comment]
@IlyaZavalov

**Comment by Alex2772** [comment]
Still broken

**Comment by Alex2772** [comment]
Complete
