### ISSUE TITLE
Grid splitter stange behaviour in aui.example.views

### ISSUE THREAD

**Issue by Alex2772** [aui-framework/aui#310]
#304 

The grid splitter seems to behave erratically, I can get it outside of the window, the last cell of the first row grows more than the others, and it resets itself to the initial position all the time.

It would be nice to implement cursors to react on all splitters.

**Comment by na2axl** [comment]
I think we can also add to this that when resizing a splitter, the window min size becomes fixed to the initial splitter size before resizing, and the splitter max size becomes fixed to the largest size it has after resizing.

There is an example explaining what I mean:

https://github.com/user-attachments/assets/ae0de412-d599-406e-8218-293dbd6d4fc0

The last time I tried the example project I got the same issue.

**Comment by Alex2772** [comment]
> I think we can also add to this that when resizing a splitter, the window min size becomes fixed to the initial splitter size before resizing, and the splitter max size becomes fixed to the largest size it has after resizing.
> 
> There is an example explaining what I mean:
> 
>  Screen.Recording.2024-12-09.085033.mp4 
> The last time I tried the example project I got the same issue.

Which window class do you use here, `ACustomCaptionWindow` or `ACustomWindow`?

**Comment by Alex2772** [comment]
@na2axl 
I've looked at your example again (good job btw!) and noticed that your layout is not actually grid. I think you use nested `ASplitter`s. Please correct me if I'm wrong.

**Comment by na2axl** [comment]
Hey @Alex2772,

I'm using `ACustomCaptionWindow` here.

For the splitter, no I'm not using nested splitter. The only resizable area is the one shown in the video. The Logs section and the Pipelines section are both fixed.

My layout can be resumed to be:

```
Vertical::Expanded
  Splitter::Horizontal::Expanded
    Vertical
       AssetsPanel
       PipelinePanel::FixedSize
     PropertiesPanel::Expanded
  LogsPanel::FixedSize
```

I may add more details if needed. And thanks for the compliment about the app design, all of that is due to this awesome lib ❤️
