### ISSUE TITLE
Multi-windows apps broken on MacOS

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#324]
Hey @Alex2772, I've been trying my app on a Mac (I know MacOS is not yet fully supported). It seems that opening more than one window does not work, the first one is displayed properly but any other window are filled with a red texture, but it seems that events are still triggered (if you know the position of a button and click on that position, the button's action will be triggered), so I think the issue may come from the renderer.

For my app it open a splash screen first and then a welcome screen. Everything after the splash screen got the red texture. If I remove the splash screen it shows the welcome screen properly, but anything after got the red texture.

I will check if the example app have the same issue.

**Comment by Alex2772** [comment]
Hi @na2axl,

Could you please clarify intel or arm based mac are you using?

**Comment by na2axl** [comment]
ARM, a M2 chip

**Comment by Alex2772** [comment]
The issue can be definitely reproduced on examples.

<img width="815" alt="Screenshot 2024-09-17 at 23 30 04" src="https://github.com/user-attachments/assets/fc460a84-dce1-457e-bea6-d9cda08afd3c">

**Comment by Alex2772** [comment]
Please be careful: sounds on macs are also broken 😨 works on ios though

**Comment by Alex2772** [comment]
@na2axl macos support is still "in dev". Let us know if you find new issues!

**Comment by Alex2772** [comment]
@na2axl hi there, have you tested this issue?
