### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by Linuxuser1234** [aui-framework/aui#329]
Im trying to install the aui framework on Code::Blocks IDE i downloaded glibc because it was complaning about spawn.h not being found in pipe.h  
but now im getting this error
```
||=== Build: Release in boltwxFE (compiler: GNU GCC Compiler) ===|
libs\aui\aui.core\src\AUI\Platform\glibc\include\features-time64.h|1|fatal error: features-time64.h: No such file or directory|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
```
in C::B i have included the file where features-times64.h is but it is not finding it 
this is the line it complaning about in features-times64.h
`#include_next <features-time64.h>`
i am on windows 11

**Comment by Alex2772** [comment]
Hi,

Please use cmake with Ninja or Visual Studio generator to build. MinGW is not fully supported.

```
git clone https://github.com/aui-framework/aui/
cd aui
mkdir build
cd build
cmake .. -G "Visual Studio 16 2019" # or whatever you use
cmake --build .
```

Please note that MSVC binaries may not be compatible with MinGW.
