### ISSUE TITLE
Renderer broken?

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#343]
Hey @Alex2772,

I just moved my project to the latest develop. Had to do some migration changes (especially with the new _unique type) and everything compiled successfully. But when launching the app, the window content displays itself in a very small space of the window. In my screenshot the lighter box in the upper-left is actually the entire window content.

![image](https://github.com/user-attachments/assets/d21d3607-c0a8-4222-97f8-9b6610322620)

This is actually the case with every other windows.

**Comment by Alex2772** [comment]
Does the devtools (ctrl+f12) window works? Can you make a screenshot of devtools window?

**Comment by na2axl** [comment]
![image](https://github.com/user-attachments/assets/35ef656c-cad7-4657-8b03-8024653460e5)

That's the result after I've clicked on `Force Layout Update`. The widgets are still kind of collapsed to the upper left of the window

**Comment by na2axl** [comment]
But since the Devtool window is displayed properly, does that means the issue is coming from my app only? Because I started to doubt that when I tried to fix it by removing every custom styling thinking maybe there are breaking changes here too, but even with the base style I have the same issue. I also wanted to check the examples but they are not running, complaining about a missing DLL, (sox.dll IIRC)

**Comment by Alex2772** [comment]
I've pushed possible tryfix to develop. Waiting for feedback.

Also, AUI has an issue when some interfaces need several frames in order to display properly. I'll file a dedicated issue for that later.

**Comment by na2axl** [comment]
Still having the same issue with your fix.

**Comment by Alex2772** [comment]
This is sad :(

There are 2 options to suggest:

1. Try to make a small example which reproduces your issue.
2. Try your code with different commits from develop branch, you’d probably find a specific commit which breaks your layout

**Comment by na2axl** [comment]
Just tried with the simplest window of my app (the splashscreen), a custom window that just displays an image, but still pushed on the upper left.

![image](https://github.com/user-attachments/assets/3a49ab8f-31d9-4e59-b230-5df603e01640)

The window code is the following:
```cpp
SplashWindow::SplashWindow()
  : ACustomWindow("Amplitude Studio", 600_dp, 400_dp)
{
  setLayout(_unique<AStackedLayout>());
  setWindowStyle(WindowStyle::MODAL);

  addView(Icon { ":img/brand/splashscreen.svg" } with_style { FixedSize { 600_dp, 400_dp } });
  addView(Horizontal::Expanding {
    Vertical::Expanding {
      Label { "v1.0.0" },
      SpacerExpanding { },
      Label { "Checking License..." }
    },
  } with_style { Padding { 8_dp } });
}
```

**Comment by na2axl** [comment]
Ok, I finally got the issue. I assumed the `_unique` type was a function 🤦🏾‍♂️, and updated all my `setLayout` calls to change `_new` to `_unique`. I figured out it's just an alias to `std::unique_ptr` so I was passing a null layout every time.

Changing them to `std::make_unique` calls fixed the issues. Sorry about that.

**Comment by Alex2772** [comment]
@na2axl I wonder why do you use `setLayout` / `addView` if there's `setContents`? https://aui-framework.github.io/master/md_docs_Getting_started_with_AUI.html

**Comment by na2axl** [comment]
Thanks for pointing it, the window was one of the first one I did when I was still learning AUI. There are a lot more places like this 😅. I will probably refactor many things since I'm restating the work on that project.
