### ISSUE TITLE
Technical background of AUI

### ISSUE THREAD

**Issue by olidevelop** [aui-framework/aui#352]
Hi Alex,
I found your AUI Framework more or less by accident when looking for a declarative UI framework for C++. I find your project very promising and interesting! I wonder if there are any "real life projects" build with AUI. Do you have a kind of roadmap? Where can I read something about the technical background, a very rough summary would be nice, just to get a picture of how the framework is implemented.
Thank you
Oliver

**Comment by Alex2772** [comment]
Hi @olidevelop,

Thank you for interest!

1. As far as I know, there are several private (i.e., unpublished) projects using AUI (including those that i'm not taking part in). I'm planning to set up a list of projects that use AUI, but unfortunately there aren't many guys who wants to be referenced :( There's one client application which is in production state and built entirely in AUI - google "magicsea online"
2. We don't have roadmap. Our target roadmap is to support Android + iOS and cover these issues that is currently open on our GitHub page.
3. The framework is inspired by Jetpack compose, SwiftUI and QML, and tries to resemble them. Rendering routines are made with OpenGL. Dependency management is made in pure CMake. Let me know if it is not enough :)

**Comment by olidevelop** [comment]
Hi Alex,
thank you. Perhaps one more question, a more personal one, you certainly don't need to answer, if you don't want to. What is your personal motivation to put much effort into such a project (I know there are also some contributors).
Best regards
Oliver

**Comment by Alex2772** [comment]
Hi @olidevelop,

I personally want a rock solid free basis with ui, network capabilities and other handy stuff that can be shared between my projects. I like the idea that UI and business logic can be made with one single language without involving others (QML).

I've started this project as a personal as well and now supporting AUI is part of my job.

**Comment by Alex2772** [comment]
Stalled. Feel free to reopen.
