### ISSUE TITLE
`SpacerFixed` not working properly

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#356]
Hey @Alex2772,

I have issues with `SpacerFixed` not working anymore (that issue is there for a while now). The view doesn't have any spacing effect, acting like it initially has a `GONE` visibility. But if you open the dev tools and click on the `Force Layout Update` button, all the `SpacerFixed` views works now.

Ex: Before `Force Layout Update`
![image](https://github.com/user-attachments/assets/c5706677-f796-4645-8705-e69a9c94029d)

After `Force Layout Update`
![image](https://github.com/user-attachments/assets/b68a8ef2-b89d-4cff-92ef-377b08ae0efc)

**Comment by Alex2772** [comment]
Hi @na2axl,

It's definitely something wrong with `SpacerFixed`. We used to have exact similar problem.

As a workaround, you may call `applyGeometryToChildrenIfNecessary` to parent container where `SpacerFixed` lives.

I'll keep this issue open to track it.

**Comment by Alex2772** [comment]
Nice IntelliJ-style mockup btw ;)

**Comment by na2axl** [comment]
Hey @Alex2772,
I've tried your workaround in many ways but without being able to make it work. I'm not sure of when I should call this method. Currently I call it in the constructor of my views, tried also in a `let` of the parent view but nothing.

**Comment by na2axl** [comment]
@Alex2772
Just to mention that with the merged PR, the issue is fixed, thanks!
