### ISSUE TITLE
How to connect signal with parameters?

### ISSUE THREAD

**Issue by malik1988** [aui-framework/aui#367]
Could you please show how to connect signal with parameters? Especially when want to get current state of a control, ATreeView for the example, I want to get current selected item information and do some logical control to change views.

**Comment by Alex2772** [comment]
Hi @malik1988,

Just add the desired argument to your receiver:

```cpp
auto treeView = _new<ATreeView>();
connect(treeView->itemSelected, [](ATreeModelIndex index){
  // ...
});
```

**Comment by malik1988** [comment]
Thanks, 
 1. but, I tried as below ,got `[UI thread][SignalHandler][ERR]: Caught signal: Segmentation fault(11)`.
 ```c++
auto model=_new<ATreeModel<AString>>(AVector<ATreeModel<AString>::Item>{
                              {
                                .value = "dir1",
                                .children = {
                                  { .value = "file1" },
                                  { .value = "file2" },
                                }
                              },
                              {
                                .value = "dir2",
                                .children = {
                                  { .value = "file3" },
                                  { .value = "file4" },
                                }
                              },
                            });

_new<ATreeView>(model).connect(&ATreeView::itemSelected,this,[this,&model](ATreeModelIndex index){                                                
                                    auto selected=model->itemAt(index);
                                    AMessageBox::show(this, "Title", fmt::format("model selected {} ",selected), AMessageBox::Icon::INFO);
                                });
```



2. By the way, can I connect a timeout signal, like gtkmm Glib::SingalTimeout::connect()  ?

**Comment by Alex2772** [comment]
1. That’s because you captured `model` by reference. `model` variable is a shared pointer so there's no need to store it in lambda by reference. Just store it by value: `[this, model]`. Similar problem: https://forum.qt.io/topic/122849/connect-with-lambda-and-capture-by-reference-causes-segmentation-fault/2
2. https://aui-framework.github.io/master/classATimer.html but you need to keep it alive by storing somewhere.

**Comment by malik1988** [comment]
Thanks, helps a lot!
