### ISSUE TITLE
Allow `AProcess::make` to get a custom `AStringVector` of args

### ISSUE THREAD

**Issue by na2axl** [aui-framework/aui#397]
The current implementation of `AProcess::make` takes a string as arguments, and manually splits it by spaces to build the list of args. Doing this way breaks things on Linux where for example, a single argument contains a space (ex: a directory/file name with a space), and it's difficult to have a cross-platform solution for this case. I think the best approach would be to let the developer build the array of args manually.

**Comment by Alex2772** [comment]
We can make an overload that accepts `AStringVector`. This way we wouldn't break existing code. The described problem will be solved.

**Comment by Alex2772** [comment]
How do you deal with arguments with spaces on Windows? By wrapping with quots?

**Comment by na2axl** [comment]
Yes, wrapping with quotes works on Windows, but not on Linux. Linux seems to use the quote as is in the parameter value. Maybe because the command is not running in a shell?

**Comment by Alex2772** [comment]
I think you are right. Anyway, I'd prefer support both "full command line" (Windows style) and arguments list (Unix style).

**Comment by Alex2772** [comment]
Merged to `develop`. Feel free to reopen if you encounter any issues.
